### PR TITLE
Fix settings deprecation

### PR DESCRIPTION
**Pull request by lee-dohm**
Deprecated APIs are going to be removed on June 1st. This appears to fix the only deprecation in your package.

### CODE REVIEW

**Comment by pcasaretto** [comment]
Thanks!
Also, I haven't used treetop in a while.
Maybe you are interested in taking ownership of this package? :)

**Comment by lee-dohm** [comment]
I don't use it often, but sure ... I wouldn't mind taking ownership of it.

**Comment by pcasaretto** [comment]
Cool.
So I just transfer the repo to you?

**Comment by lee-dohm** [comment]
For now, just add me as a collaborator. I'll see how we can transfer it after that without breaking the publishing permissions.

**Comment by pcasaretto** [comment]
Done!

**Comment by lee-dohm** [comment]
According to the Atom Core team, you can just transfer the repository to me and everything will be fine. I've deleted my fork of it, so everything should be ready when you are.

**Comment by pcasaretto** [comment]
Transfer requested!

**Pull request merged**
